server:
  port: 8090

spring:
  application:
    name: flowable

  datasource:
    url: jdbc:postgresql://localhost:5433/flowable
    username: flowable
    password: flowable
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true